### ISSUE TITLE
What is this repo for?

### ISSUE THREAD

**Issue by Milk-Cool** [Spu7Nix/COLLAPSE#1]
Maybe add a readme?

**Comment by farkon00** [comment]
Good question. @Spu7Nix

**Comment by Spu7Nix** [comment]
It's a programming language for the third [langjam](https://github.com/langjam/langjam), which i never finished

**Comment by Milk-Cool** [comment]
> It's a programming language for the third [langjam](https://github.com/langjam/langjam), which i never finished

Alright, thanks for the reply. Closing the issue.
